### ISSUE TITLE
match utility

### ISSUE THREAD

**Issue by JoshRosenstein** [bupa-digital/shades#1]
Hi, i dont think you are currently using this function anywhere, but if you did, might want to do: 
valueAsFunction(matchers[value])(value).

I'm new to coding, and have been leaning more towards functional programming techniques, so i've just been looking up other peoples functional utilities and just been walking through them for self development.  But i do like where you're heading with the library.

Your methodology for dynamic styles reminds me of styled-theming utility from styled-components, but applying across all props and not just the theme prop.  
I tried rebuilt my own css-js helper library like styled-system, just for learning, and i tried to come up with a way to make it more dynamic rules kinda like you are doing. 

I'll be keeping an eye on this. Great work

https://github.com/bupa-digital/shades/blob/3e708c762652418cfe9d8534177e71d5833267e0/src/utilities.js#L195

**Comment by MiracleBlue** [comment]
Howdy, thanks!

I, too, favour reading lots of other people's code on things, especially FP principles.  It's been the most helpful learning tool for me.

That Match utility was an early attempt to solve the pattern-matching functionality, which I ended up just building into the style-parser directly rather than as its own helper method.

Had I continued with that utility, I probably would have wrapped it in valueAsFunction.

Thanks for the kind words!
